#!/bin/bash
set -e
set -x

#(cd .. && make minire BONUS=1 TEST=1 DEBUG=1 HEADLESS=1)
#../tester > test_output
#diff test_output correct_test_output

(cd .. && make minire DEBUG=1 HEADLESS=1)
(cd .. && ./miniRT tests/test_no_spot.rt)
(cd .. && ./miniRT mandatory.rt)
(cd .. && ./miniRT tests/empty.rt 2> tests/empty_output) || true; diff empty_output empty_correct_output

make -C .. minire BONUS=1 DEBUG=1 HEADLESS=1
(cd .. && ./miniRT bonus.rt)
../miniRT empty.rt 2> empty_output || true; diff empty_output empty_correct_output
(cd .. && ./miniRT tests/space_missing.rt 2> tests/output) || true; diff output parse_error_correct_output
(cd .. && ./miniRT tests/ 2> tests/output) || true; diff output float_not_in_range_correct_output

